const lists = {
	"todo": [
		"Write tasks below 👇"
	],
	"daily": [
		"Put clothes on 👕",
		"Eat Breakfast 🍱",
		"Fill the water bottle 🍼",
		"Put shoes on 👟",
		"Comb hair 💆"
	],
	"homework": [
		"Spelling 📝",
		"Maths 📐",
		"Book 📗",
		"Polski 🇵🇱"
	],
	"usa": [
		"Flipflops 🩴",
		"Sandals 👡",
		"Bathing Suit 🩱",
		"Cap 🧢",
		"Sunglasses 🕶️",
		"Shorts 🩳",
		"Sports T-shirts 2️⃣ 👕",
		"T-shirts 3️⃣👚",
		"Panties 🔟🩲",
		"Socks 7️⃣🧦",
		"Pants 👖",
		"Hoodie/Jumper 🥼",
		"Sweater 🧥",
		"Skirt 👗",
		"PJ short",
		"PJ long",
		"Headphones 🎧"
	],
	"japan": [
		"Flipflops 🩴",
		"Bathing Suit 🩱",
		"Cap 🧢",
		"Shorts 🩳",
		"T-shirts 7️⃣👚",
		"Panties 7️⃣🩲",
		"Socks 7️⃣🧦",
		"Pants 👖",
		"Hoodie/Jumper 🥼",
		"Sweater 👕🦺",
		"Jacket 🧥",
		"PJ long",
		"phone📱",
		"chargers 🔌",
		"Headphones 🎧"
	],
	"week": [
		"📥 Clean up inboxes and desk",
		"💌 Clean up Email inbox",
		"☑️ Clean up Nozbe inbox",
		"💻 Clean up Downloads folder",
		"💪 Review your goals",
		"🗓️ Review last week’s calendar",
		"⏰ Check what’s coming next week",
		"✅ Go through each of your projects",
		"⁉️ Ask yourself: does it belong here? Is it still relevant? Is there anything new to be added here? Is the due date realistic?",
		"✔️ Complete some projects and clean up to focus on the essential.",
		"✍️ Set your new goals for next week",
		"📝 Plan next week, block times for deep work",
		"🎉 Celebrate a weekly review done well!"
	],
	"uk": [
		"🎒 SMALL BACKPACK with only necessary stuff",
		"📱 iPad + chargers",
		"👕 4 t-shirts",
		"🩲 3 pairs of underwear",
		"🧦 3 pairs of socks",
		"🥼 hoodie / crewneck",
		"🥼 sweater",
		"👖 long pants and leggins",
		"🧥 jacket",
		"💤 PJ long-sleeved",
		"🧢 Cap",
		"🥾 Shoes for UK",
		"🧴 Cosmetics"
	],
	"trip": [
		"🎒 SMALL BACKPACK with water bottle and a game, book, or similar item",
		"🪥 Toiletry bag: comb or brush, shower gel and shampoo toothbrush and toothpaste, etc.",
		"💼 SMALL SUITCASE or SOFT BAG labelled with name",
		"👕 4 t-shirts",
		"🩳 2 pairs of shorts",
		"🩲 3 pairs of underwear",
		"🧦 3 pairs of socks",
		"🏊 Swimwear including t-shirts for aquatic activities",
		"👟 Sports trainers/sneakers",
		"👞 Water shoes or swim shoes (reef shoes)",
		"🩴 Flip-flops for the shower",
		"🥼 long-sleeved shirt",
		"👖 long pants",
		"🧥 Fleece jacket or similar",
		"💤 PJ - long-sleeved pajamas",
		"🌛 Pillow (optional)",
		"🏖️ Bath towel and a hand towel",
		"🛍️ A plastic bag (to store dirty clothes, wet towel, etc.)",
		"🌧️ Raincoat or windbreaker for sailing",
		"🧢 Cap",
		"🧴 Suncreme",
		"🕶️ Sunglasses (optional)",
		"🦟 Mosquito repellent",
		"🧸 (Optional) A small game (cards, Rubik’s cube, small night-time plush toy...), book.."
	]
};